# Generated by Django 2.2 on 2020-12-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='新增时间')),
                ('create_user', models.IntegerField(blank=True, verbose_name='创建者')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='最新修改时间')),
                ('update_user', models.IntegerField(blank=True, verbose_name='修改者')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('nick_name', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='female', max_length=6)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('image', models.FileField(default='image/default_head_image.jpg', upload_to='image/%Y/%m')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
