from django.test import TestCase

# Create your tests here.

import sys
import os

pwd = os.path.dirname(os.path.realpath(__file__))
sys.path.append(pwd + '../')

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'django_auth_admin.settings')

import django

django.setup()

a = {
    "code": 1000,
    "message": "success",
    "data": [
        {
            "id": "48",
            "createTime": "2019-11-08 09:35:53",
            "updateTime": "2019-11-08 09:37:02",
            "parentId": "47",
            "name": "文档",
            "router": "/tutorial/doc",
            "perms": "",
            "type": 1,
            "icon": "icon-log",
            "orderNum": 0,
            "viewPath": "https://docs-admin-pro.cool-js.com/#/?id=%E7%AE%80%E4%BB%8B",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "教程"
        },
        {
            "id": "59",
            "createTime": "2019-11-18 16:50:27",
            "updateTime": "2019-11-18 16:50:27",
            "parentId": "17",
            "name": "部门列表",
            "router": "",
            "perms": "sys:department:list",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "60",
            "createTime": "2019-11-18 16:50:45",
            "updateTime": "2019-11-18 16:50:45",
            "parentId": "17",
            "name": "新增部门",
            "router": "",
            "perms": "sys:department:add",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "61",
            "createTime": "2019-11-18 16:50:59",
            "updateTime": "2019-11-18 16:50:59",
            "parentId": "17",
            "name": "更新部门",
            "router": "",
            "perms": "sys:department:update",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "62",
            "createTime": "2019-11-18 16:51:13",
            "updateTime": "2019-11-18 16:51:13",
            "parentId": "17",
            "name": "删除部门",
            "router": "",
            "perms": "sys:department:delete",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "63",
            "createTime": "2019-11-18 17:49:35",
            "updateTime": "2019-11-18 17:49:35",
            "parentId": "17",
            "name": "部门排序",
            "router": "",
            "perms": "sys:department:order",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "65",
            "createTime": "2019-11-18 23:59:21",
            "updateTime": "2019-11-18 23:59:21",
            "parentId": "17",
            "name": "用户转移",
            "router": "",
            "perms": "sys:user:move",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "67",
            "createTime": "2019-11-26 23:50:13",
            "updateTime": "2019-11-26 23:50:13",
            "parentId": "66",
            "name": "记录",
            "router": "",
            "perms": "sys:info:record",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "服务状态"
        },
        {
            "id": "71",
            "createTime": "2019-12-10 13:25:33",
            "updateTime": "2019-12-10 13:25:33",
            "parentId": "70",
            "name": "新增",
            "router": "",
            "perms": "sys:task:add",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "任务列表"
        },
        {
            "id": "72",
            "createTime": "2019-12-10 13:25:45",
            "updateTime": "2019-12-10 13:25:45",
            "parentId": "70",
            "name": "删除",
            "router": "",
            "perms": "sys:task:delete",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "任务列表"
        },
        {
            "id": "73",
            "createTime": "2019-12-10 13:26:03",
            "updateTime": "2019-12-10 13:26:18",
            "parentId": "70",
            "name": "修改",
            "router": "",
            "perms": "sys:task:info,sys:task:update",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "任务列表"
        },
        {
            "id": "74",
            "createTime": "2019-12-10 13:26:49",
            "updateTime": "2019-12-10 13:26:49",
            "parentId": "70",
            "name": "查看",
            "router": "",
            "perms": "sys:task:page,sys:task:info,sys:task:log",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "任务列表"
        },
        {
            "id": "75",
            "createTime": "2019-12-10 13:27:10",
            "updateTime": "2019-12-10 13:27:10",
            "parentId": "70",
            "name": "立即执行",
            "router": "",
            "perms": "sys:task:once",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "任务列表"
        },
        {
            "id": "76",
            "createTime": "2019-12-10 13:27:24",
            "updateTime": "2019-12-10 13:27:24",
            "parentId": "70",
            "name": "开始",
            "router": "",
            "perms": "sys:task:start",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "任务列表"
        },
        {
            "id": "77",
            "createTime": "2019-12-10 13:27:36",
            "updateTime": "2019-12-10 13:27:36",
            "parentId": "70",
            "name": "暂停",
            "router": "",
            "perms": "sys:task:stop",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "任务列表"
        },
        {
            "id": "79",
            "createTime": "2019-12-10 13:29:33",
            "updateTime": "2019-12-10 13:29:33",
            "parentId": "78",
            "name": "参数列表",
            "router": "/sys/param",
            "perms": "",
            "type": 1,
            "icon": "icon-menu",
            "orderNum": 0,
            "viewPath": "views/system/param/index.vue",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "参数配置"
        },
        {
            "id": "80",
            "createTime": "2019-12-10 13:29:50",
            "updateTime": "2019-12-10 13:29:50",
            "parentId": "79",
            "name": "新增",
            "router": "",
            "perms": "sys:param:add",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "参数列表"
        },
        {
            "id": "81",
            "createTime": "2019-12-10 13:30:10",
            "updateTime": "2019-12-10 13:30:10",
            "parentId": "79",
            "name": "修改",
            "router": "",
            "perms": "sys:param:info,sys:param:update",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "参数列表"
        },
        {
            "id": "82",
            "createTime": "2019-12-10 13:30:25",
            "updateTime": "2019-12-10 13:30:25",
            "parentId": "79",
            "name": "删除",
            "router": "",
            "perms": "sys:param:delete",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "参数列表"
        },
        {
            "id": "83",
            "createTime": "2019-12-10 13:30:40",
            "updateTime": "2019-12-10 13:30:40",
            "parentId": "79",
            "name": "查看",
            "router": "",
            "perms": "sys:param:page,sys:param:list,sys:param:info",
            "type": 2,
            "icon": "",
            "orderNum": 0,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "参数列表"
        },
        {
            "id": "1",
            "createTime": "2019-09-11 11:14:44",
            "updateTime": "2019-11-18 15:56:36",
            "parentId": "",
            "name": "工作台",
            "router": "/",
            "perms": "",
            "type": 0,
            "icon": "icon-workbench",
            "orderNum": 1,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1
        },
        {
            "id": "10",
            "createTime": "2019-09-12 00:19:27",
            "updateTime": "2019-09-12 00:19:27",
            "parentId": "8",
            "name": "新增",
            "router": "",
            "perms": "sys:menu:add",
            "type": 2,
            "icon": "",
            "orderNum": 1,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "菜单列表"
        },
        {
            "id": "17",
            "createTime": "2019-09-12 00:31:25",
            "updateTime": "2019-09-15 23:45:57",
            "parentId": "27",
            "name": "用户列表",
            "router": "/sys/user",
            "perms": "",
            "type": 1,
            "icon": "icon-user-fill",
            "orderNum": 1,
            "viewPath": "views/system/user/index.vue",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "权限管理"
        },
        {
            "id": "18",
            "createTime": "2019-09-12 00:32:21",
            "updateTime": "2019-11-09 22:22:19",
            "parentId": "17",
            "name": "新增",
            "router": "",
            "perms": "sys:user:add",
            "type": 2,
            "icon": "",
            "orderNum": 1,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "23",
            "createTime": "2019-09-12 00:34:23",
            "updateTime": "2019-09-12 00:34:23",
            "parentId": "22",
            "name": "新增",
            "router": "",
            "perms": "sys:role:add",
            "type": 2,
            "icon": "",
            "orderNum": 1,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "角色列表"
        },
        {
            "id": "27",
            "createTime": "2019-09-12 15:52:44",
            "updateTime": "2019-09-15 22:11:56",
            "parentId": "2",
            "name": "权限管理",
            "router": "",
            "perms": "",
            "type": 0,
            "icon": "icon-auth",
            "orderNum": 1,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "系统"
        },
        {
            "id": "29",
            "createTime": "2019-09-12 17:35:51",
            "updateTime": "2019-11-26 23:46:53",
            "parentId": "28",
            "name": "请求日志",
            "router": "/sys/log",
            "perms": "",
            "type": 1,
            "icon": "icon-log",
            "orderNum": 1,
            "viewPath": "views/system/log/index.vue",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "系统监控"
        },
        {
            "id": "30",
            "createTime": "2019-09-12 17:37:03",
            "updateTime": "2019-11-18 14:20:27",
            "parentId": "29",
            "name": "权限",
            "router": "",
            "perms": "sys:log:page,sys:log:clear,sys:log:get-keep,sys:log:set-keep",
            "type": 2,
            "icon": "",
            "orderNum": 1,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "请求日志"
        },
        {
            "id": "43",
            "createTime": "2019-11-07 14:22:34",
            "updateTime": "2019-11-09 22:11:18",
            "parentId": "45",
            "name": "crud 示例",
            "router": "/crud",
            "perms": "",
            "type": 1,
            "icon": "icon-radioboxfill",
            "orderNum": 1,
            "viewPath": "views/test/crud.vue",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "组件库"
        },
        {
            "id": "53",
            "createTime": "2019-11-11 15:21:00",
            "updateTime": "2019-11-11 15:21:00",
            "parentId": "1",
            "name": "组件预览",
            "router": "/ui-components",
            "perms": "",
            "type": 1,
            "icon": "icon-menu",
            "orderNum": 1,
            "viewPath": "views/workbench/ui-components",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "工作台"
        },
        {
            "id": "70",
            "createTime": "2019-12-10 13:25:06",
            "updateTime": "2019-12-10 13:28:53",
            "parentId": "69",
            "name": "任务列表",
            "router": "/sys/task",
            "perms": "",
            "type": 1,
            "icon": "icon-menu",
            "orderNum": 1,
            "viewPath": "views/system/task/index.vue",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "任务管理"
        },
        {
            "id": "85",
            "createTime": "2020-07-25 16:22:14",
            "updateTime": "2020-07-25 16:22:14",
            "parentId": "84",
            "name": "图片上传",
            "router": "",
            "perms": "app:space:info:page,app:space:info:add,app:space:info:delete,app:space:type:list,app:space:type:add,app:space:type:delete,app:space:type:update",
            "type": 2,
            "icon": "",
            "orderNum": 1,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "通用"
        },
        {
            "id": "2",
            "createTime": "2019-09-11 11:14:47",
            "updateTime": "2019-09-18 15:37:18",
            "parentId": "",
            "name": "系统",
            "router": "/sys",
            "perms": "",
            "type": 0,
            "icon": "icon-system-fill",
            "orderNum": 2,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1
        },
        {
            "id": "8",
            "createTime": "2019-09-11 23:19:57",
            "updateTime": "2019-09-12 15:53:39",
            "parentId": "27",
            "name": "菜单列表",
            "router": "/sys/menu",
            "perms": "",
            "type": 1,
            "icon": "icon-menu",
            "orderNum": 2,
            "viewPath": "views/system/menu/index.vue",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "权限管理"
        },
        {
            "id": "11",
            "createTime": "2019-09-12 00:19:51",
            "updateTime": "2019-09-12 00:19:51",
            "parentId": "8",
            "name": "删除",
            "router": "",
            "perms": "sys:menu:delete",
            "type": 2,
            "icon": "",
            "orderNum": 2,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "菜单列表"
        },
        {
            "id": "19",
            "createTime": "2019-09-12 00:32:34",
            "updateTime": "2019-09-12 00:32:34",
            "parentId": "17",
            "name": "删除",
            "router": "",
            "perms": "sys:user:delete",
            "type": 2,
            "icon": "",
            "orderNum": 2,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "24",
            "createTime": "2019-09-12 00:34:40",
            "updateTime": "2019-09-12 00:34:40",
            "parentId": "22",
            "name": "删除",
            "router": "",
            "perms": "sys:role:delete",
            "type": 2,
            "icon": "",
            "orderNum": 2,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "角色列表"
        },
        {
            "id": "28",
            "createTime": "2019-09-12 17:19:16",
            "updateTime": "2019-09-15 22:12:08",
            "parentId": "2",
            "name": "系统监控",
            "router": "",
            "perms": "",
            "type": 0,
            "icon": "icon-monitor",
            "orderNum": 2,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "系统"
        },
        {
            "id": "45",
            "createTime": "2019-11-07 22:36:57",
            "updateTime": "2019-11-11 15:21:10",
            "parentId": "1",
            "name": "组件库",
            "router": "/ui-lib",
            "perms": "",
            "type": 0,
            "icon": "icon-common",
            "orderNum": 2,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "工作台"
        },
        {
            "id": "49",
            "createTime": "2019-11-09 22:11:13",
            "updateTime": "2019-11-09 22:11:34",
            "parentId": "45",
            "name": "Quill 富文本",
            "router": "/editor-quill",
            "perms": "",
            "type": 1,
            "icon": "icon-radioboxfill",
            "orderNum": 2,
            "viewPath": "views/test/editor-quill.vue",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "组件库"
        },
        {
            "id": "66",
            "createTime": "2019-11-26 23:48:16",
            "updateTime": "2019-11-26 23:48:29",
            "parentId": "28",
            "name": "服务状态",
            "router": "/sys/perf",
            "perms": "",
            "type": 1,
            "icon": "icon-warn-fill",
            "orderNum": 2,
            "viewPath": "views/system/perf/index.vue",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "系统监控"
        },
        {
            "id": "12",
            "createTime": "2019-09-12 00:20:05",
            "updateTime": "2019-09-12 00:20:05",
            "parentId": "8",
            "name": "修改",
            "router": "",
            "perms": "sys:menu:update",
            "type": 2,
            "icon": "",
            "orderNum": 3,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "菜单列表"
        },
        {
            "id": "20",
            "createTime": "2019-09-12 00:32:47",
            "updateTime": "2019-09-12 00:32:47",
            "parentId": "17",
            "name": "修改",
            "router": "",
            "perms": "sys:user:update",
            "type": 2,
            "icon": "",
            "orderNum": 3,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "22",
            "createTime": "2019-09-12 00:34:01",
            "updateTime": "2019-09-15 23:47:27",
            "parentId": "27",
            "name": "角色列表",
            "router": "/sys/role",
            "perms": "",
            "type": 1,
            "icon": "icon-common",
            "orderNum": 3,
            "viewPath": "views/system/role/index.vue",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "权限管理"
        },
        {
            "id": "25",
            "createTime": "2019-09-12 00:34:53",
            "updateTime": "2019-09-12 00:34:53",
            "parentId": "22",
            "name": "修改",
            "router": "",
            "perms": "sys:role:update",
            "type": 2,
            "icon": "",
            "orderNum": 3,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "角色列表"
        },
        {
            "id": "47",
            "createTime": "2019-11-08 09:35:08",
            "updateTime": "2019-11-08 19:44:44",
            "parentId": "",
            "name": "教程",
            "router": "/tutorial",
            "perms": "",
            "type": 0,
            "icon": "icon-task",
            "orderNum": 3,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1
        },
        {
            "id": "69",
            "createTime": "2019-12-10 13:24:18",
            "updateTime": "2019-12-10 13:24:18",
            "parentId": "2",
            "name": "任务管理",
            "router": "",
            "perms": "",
            "type": 0,
            "icon": "icon-task",
            "orderNum": 3,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "系统"
        },
        {
            "id": "86",
            "createTime": "2020-08-12 09:56:27",
            "updateTime": "2020-08-12 09:56:27",
            "parentId": "45",
            "name": "Upload 上传组件",
            "router": "/upload",
            "perms": "",
            "type": 1,
            "icon": "icon-radioboxfill",
            "orderNum": 3,
            "viewPath": "views/test/upload.vue",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "组件库"
        },
        {
            "id": "13",
            "createTime": "2019-09-12 00:20:19",
            "updateTime": "2019-09-12 00:20:19",
            "parentId": "8",
            "name": "查询",
            "router": "",
            "perms": "sys:menu:page,sys:menu:list,sys:menu:info",
            "type": 2,
            "icon": "",
            "orderNum": 4,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "菜单列表"
        },
        {
            "id": "21",
            "createTime": "2019-09-12 00:33:00",
            "updateTime": "2019-09-12 00:33:00",
            "parentId": "17",
            "name": "查询",
            "router": "",
            "perms": "sys:user:page,sys:user:list,sys:user:info",
            "type": 2,
            "icon": "",
            "orderNum": 4,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "用户列表"
        },
        {
            "id": "26",
            "createTime": "2019-09-12 00:35:05",
            "updateTime": "2019-09-12 00:35:05",
            "parentId": "22",
            "name": "查询",
            "router": "",
            "perms": "sys:role:page,sys:role:list,sys:role:info",
            "type": 2,
            "icon": "",
            "orderNum": 4,
            "viewPath": "",
            "keepAlive": 0,
            "isShow": 1,
            "parentName": "角色列表"
        },
        {
            "id": "78",
            "createTime": "2019-12-10 13:27:56",
            "updateTime": "2019-12-10 13:28:37",
            "parentId": "2",
            "name": "参数配置",
            "router": "",
            "perms": "",
            "type": 0,
            "icon": "icon-common",
            "orderNum": 4,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 1,
            "parentName": "系统"
        },
        {
            "id": "84",
            "createTime": "2020-07-25 16:21:30",
            "updateTime": "2020-07-25 16:21:30",
            "parentId": "",
            "name": "通用",
            "router": "",
            "perms": "",
            "type": 0,
            "icon": "icon-radioboxfill",
            "orderNum": 99,
            "viewPath": "",
            "keepAlive": 1,
            "isShow": 0
        }
    ]
}

from users.models import Menu

c = []
for i in a['data']:
    if i['type'] == 2:
        c.append(
            Menu(**dict(
                id=i["id"],
                name=i["name"],
                path=i["router"],
                parent_id=i["parentId"],
                type=i["type"],
                icon=i["icon"],
                order_num=i["orderNum"],
                view_path=i["viewPath"],
                is_keep_alive=i["keepAlive"],
                is_show=i["isShow"],
                create_user=1,
                update_user=1
            ))
        )
print(c)
Menu.objects.bulk_create(c)

# env = EventNew.objects.select_related("event_test2").all()
# for i in env:
#     print(i.event_test2)
#     # print(i.event_test.name)
# env2 = EventNew.objects.prefetch_related("event_test").all()
# for j in env2:
#     for i in j.event_test.all():
#         print(i.name)


from users.models import TreeTest
rock = TreeTest.objects.create(name="Rock")
blues = TreeTest.objects.create(name="Blues")
TreeTest.objects.create(name="Hard Rock", parent=rock)
TreeTest.objects.create(name="Pop Rock", parent=rock)

rock1 = TreeTest.objects.create(name="Rock1")
rock101 = TreeTest.objects.create(name="Rock101", parent=rock1)
rock10101 = TreeTest.objects.create(name="rock10101", parent=rock101)
rock1010101 = TreeTest.objects.create(name="rock1010101", parent=rock10101)
rock101010101 = TreeTest.objects.create(name="rock101010101", parent=rock1010101)
rock101010102 = TreeTest.objects.create(name="rock101010102", parent=rock1010101)
rock101010103 = TreeTest.objects.create(name="rock101010103", parent=rock1010101)